@startuml Sequence Diagram for User Management Service
title Sequence Diagram for User Management Service

actor User
participant UMSController as "Service Controller"
participant UMSUseCase as "Service Use Case"
participant UMSRepository as "Service Repository"
database UDB as "User Database"

autonumber

  User -> UMSController: Send request
  activate UMSController

  UMSController -> UMSUseCase: Get user data
  activate UMSUseCase

  UMSUseCase -> UMSRepository: Retrieve user data
  activate UMSRepository

  UMSRepository -> UDB: Get user data
  activate UDB

  UDB --> UMSRepository: User data
  deactivate UDB

  UMSRepository --> UMSUseCase: User data
  deactivate UMSRepository

  UMSUseCase --> UMSController: User data
  deactivate UMSUseCase

  UMSController --> User: User data
  deactivate UMSController

@enduml
