@startuml ExistingUserLoginFlow
title Existing User Login Flow

autonumber

actor User
participant "Mobile App" as App
participant "MTNID Service" as Backend
participant "MADApi" as MADApi

User -> App: Provides phone number
App -> Backend: Sends request to fetch subscriber details
Backend -> MADApi: Fetches subscriber details
MADApi --> Backend: Returns subscriber details
Backend --> App: Returns subscriber details

App -> Backend: Sends request to generate OTP
Backend -> MADApi: Generates OTP
MADApi --> User: Sends OTP
Backend --> App: OTP request has been sent successfully
App -> App: Displays login screen with \n OTP and password fields

User -> App: Enters OTP and password
App -> Backend: Sends login request with \n phone number, OTP, and password
Backend -> MADApi: Login request
MADApi --> Backend: Login successful
Backend --> Backend: Generates token if login is successful
Backend --> App: Returns token
App -> App: Displays home screen
@enduml
